package com.mycompany.myapp;


import Tfarhida.entities.Maison;
import com.codename1.components.ImageViewer;
import com.codename1.components.MultiButton;
import static com.codename1.ui.CN.*;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Toolbar;
import java.io.IOException;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.io.NetworkEvent;
import com.codename1.ui.Button;
import static com.codename1.ui.Component.CENTER;
import static com.codename1.ui.Component.LEFT;
import com.codename1.ui.Container;
import com.codename1.ui.FontImage;
import com.codename1.ui.Image;
import com.codename1.ui.layouts.BorderLayout;

import gui.Accueil;
import gui.MaisonDHote.AddMaison;
import gui.MaisonDHote.ListMaisons;


/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {

    public Form current;
    public Resources theme;

    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if(err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });        
    }
    
    public void start() {
       
     
            if(current != null){
                current.show();
                return;
            }
            
              menu();
         
    }
    
    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }
    
    public void menu(){
           Form hi = new Form("Accueil");
            
            Toolbar tb = hi.getToolbar();
           // Image icon = theme.getImage("images/MaisonDHote/img.png");
           // Image icon = Image.createImage("/images/MaisonDHote/img.png");
            Container topBar = BorderLayout.east(new Button(""));
            topBar.setUIID("SideCommand");
            tb.addComponentToSideMenu(topBar);
            
            tb.addMaterialCommandToSideMenu("Accueil", FontImage.MATERIAL_HOME, e -> {
                new Accueil().show();
            });
            tb.addMaterialCommandToSideMenu("Maisons D'hotes", FontImage.MATERIAL_WEB, e -> {
                new ListMaisons().show();
            });
            tb.addMaterialCommandToSideMenu("Ajouter Maison", FontImage.MATERIAL_SETTINGS, e -> {
                new AddMaison().show();
            });
            tb.addMaterialCommandToSideMenu("About", FontImage.MATERIAL_INFO, e -> {});
            
            hi.addComponent(new Label("Hi World"));
            hi.show();
    }
    
    public void destroy() {
    }
    
   
    }

